gene2phenotype_project/gene2phenotype_app/urls.py
gene2phenotype_project/gene2phenotype_app/views.py

Add endpoint:
- `gene2phenotype/api/publication/<pmid>`
[G2P-124](https://www.ebi.ac.uk/panda/jira/browse/G2P-124)

Add endpoint to return publication info

---

gene2phenotype_project/gene2phenotype_app/views.py

Ticket: G2P-140
A possible drawback: the general query can be slow.

Update search endpoint to support search by G2P ID

---

gene2phenotype_project/gene2phenotype_app/views.py

Just a quick fix for creating curation records, takes curation user information now.

Accepting the user information for creating curation

---

gene2phenotype_project/gene2phenotype_app/serializers.py

Pushing the changes for serializers session name bug fix

---

gene2phenotype_project/gene2phenotype_app/models.py
gene2phenotype_project/gene2phenotype_app/serializers.py
gene2phenotype_project/gene2phenotype_app/urls.py
gene2phenotype_project/gene2phenotype_app/utils/curation_schema.json
gene2phenotype_project/gene2phenotype_app/utils/disease_utils.py
gene2phenotype_project/gene2phenotype_app/utils/phenotype_utils.py
gene2phenotype_project/gene2phenotype_app/views.py

**Please check the ticket for test instructions:** [G2P-115](https://www.ebi.ac.uk/panda/jira/browse/G2P-115)
This PR is using the current unique record: locus-genotype(allelic requirement)-disease

Add endpoint to publish a record 

---

gene2phenotype_project/gene2phenotype_app/models.py
gene2phenotype_project/gene2phenotype_app/serializers.py
gene2phenotype_project/gene2phenotype_app/views.py

- populate the molecular mechanism evidence when publishing an entry
- create new table `CVMolecularMechanism` to store the molecular mechanism values

Change db schema and populate mechanism evidence

---

requirements.txt

Upgrade requests.
Reason: 2.32.0 is a yanked version

Upgrade requirements.txt

---

gene2phenotype_project/gene2phenotype_app/models.py
gene2phenotype_project/gene2phenotype_app/serializers/__init__.py
gene2phenotype_project/gene2phenotype_app/serializers/user.py
gene2phenotype_project/gene2phenotype_app/urls.py
gene2phenotype_project/gene2phenotype_app/views/__init__.py
gene2phenotype_project/gene2phenotype_app/views/user.py
gene2phenotype_project/gene2phenotype_project/settings.py
requirements.txt

[G2P-163](https://www.ebi.ac.uk/panda/jira/browse/G2P-163)

User login management using Django Token Knox Authentication.

---

gene2phenotype_project/gene2phenotype_app/models.py

[G2P-29](https://www.ebi.ac.uk/panda/jira/browse/G2P-29)

Changes to the model for gene score probabilities

---

gene2phenotype_project/gene2phenotype_app/models.py
gene2phenotype_project/gene2phenotype_app/serializers/attrib.py
gene2phenotype_project/gene2phenotype_app/urls.py
gene2phenotype_project/gene2phenotype_app/views/__init__.py
gene2phenotype_project/gene2phenotype_app/views/attrib.py
gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py

[G2P-97](https://www.ebi.ac.uk/panda/jira/browse/G2P-97)

Endpoint for attrib description

---

gene2phenotype_project/gene2phenotype_app/serializers/locus.py
gene2phenotype_project/gene2phenotype_app/views/locus.py

Changes to add Badonyi changes to Locus API

Gene api add marsh stats

---

gene2phenotype_project/gene2phenotype_app/models.py
gene2phenotype_project/gene2phenotype_app/serializers/curation.py
gene2phenotype_project/gene2phenotype_app/views/search.py

[G2P-263](https://www.ebi.ac.uk/panda/jira/browse/G2P-263)

Search curation on gene symbol

---

gene2phenotype_project/gene2phenotype_app/serializers/disease.py
gene2phenotype_project/gene2phenotype_app/serializers/locus.py
gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/serializers/panel.py
gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/views/panel.py
gene2phenotype_project/gene2phenotype_app/views/search.py

Ticket: [G2P-299](https://www.ebi.ac.uk/panda/jira/browse/G2P-299)

Show disputed and refuted confidence to the public

---

gene2phenotype_project/gene2phenotype_app/models.py
gene2phenotype_project/gene2phenotype_app/serializers/curation.py
gene2phenotype_project/gene2phenotype_app/serializers/disease.py
gene2phenotype_project/gene2phenotype_app/serializers/locus.py
gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/serializers/panel.py
gene2phenotype_project/gene2phenotype_app/serializers/publication.py
gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/views/panel.py
gene2phenotype_project/gene2phenotype_app/views/publication.py
gene2phenotype_project/gene2phenotype_app/views/search.py

Ticket: https://www.ebi.ac.uk/panda/jira/browse/G2P-162
This PR can only be merged after the following code is merged: https://github.com/EBI-G2P/gene2phenotype_api/pull/41
DB to test: dlemos_G2P_2024_v17_new_keys

Update schema and API to make mechanism part of the unique key

---

gene2phenotype_project/gene2phenotype_app/views/panel.py
gene2phenotype_project/gene2phenotype_app/views/user.py

Ticket: [G2P-297](https://www.ebi.ac.uk/panda/jira/browse/G2P-297)

Sort panels

---

gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py

Update `gene2phenotype/api/lgd` to display user under comments.

Update LGD record endpoint to display user name

---

gene2phenotype_project/gene2phenotype_app/models.py
gene2phenotype_project/gene2phenotype_app/serializers/user.py

Set `is_superuser` to boolean (to be the same as `is_staff`)
Include 'is_superuser' and 'is_staff' in the input query and response

Update user endpoints and model

---

gene2phenotype_project/gene2phenotype_app/models.py

Ticket: [G2P-376](https://www.ebi.ac.uk/panda/jira/browse/G2P-376)
Add a table to save info about all the gencc submissions.

Update models.py - add table gencc_submission

---

gene2phenotype_project/gene2phenotype_app/views/panel.py
gene2phenotype_project/gene2phenotype_app/views/search.py

Ticket: [G2P-388](https://www.ebi.ac.uk/panda/jira/browse/G2P-388)
- Example: `11788682 -> function: biochemical, protein interaction; functional_alteration: patient cells; models: non-human model organism, cell culture model`
- all variant consequences are inferred - column renamed to 'inferred variant consequence'
Fix search: [G2P-399](https://www.ebi.ac.uk/panda/jira/browse/G2P-399)

Update download file format + fix search

---

gene2phenotype_project/gene2phenotype_app/serializers/curation.py
gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py

Ticket: [G2P-386](https://www.ebi.ac.uk/panda/jira/browse/G2P-386)

Update publish endpoint to save the phenotype summary

---

gene2phenotype_project/gene2phenotype_app/serializers/curation.py

Ticket: [G2P-348](https://www.ebi.ac.uk/panda/jira/browse/G2P-348)

Check allelic requirement when publishing record

---

gene2phenotype_project/gene2phenotype_app/serializers/curation.py

Fix this PR: https://github.com/EBI-G2P/gene2phenotype_api/pull/86

Fix error message when invalid genotype

---

gene2phenotype_project/gene2phenotype_app/views/search.py

Ticket: [G2P-431](https://www.ebi.ac.uk/panda/jira/browse/G2P-431)

Improve search - search first by gene

---

gene2phenotype_project/gene2phenotype_app/fixtures/attribs.json
gene2phenotype_project/gene2phenotype_app/fixtures/gene_disease.json
gene2phenotype_project/gene2phenotype_app/fixtures/gene_stats.json
gene2phenotype_project/gene2phenotype_app/fixtures/source.json
gene2phenotype_project/gene2phenotype_app/fixtures/uniprot_annotation.json
gene2phenotype_project/gene2phenotype_app/tests/views/test_gene.py

Ticket: [G2P-243](https://www.ebi.ac.uk/panda/jira/browse/G2P-243)

Add tests for gene endpoints

---

gene2phenotype_project/gene2phenotype_app/serializers/__init__.py
gene2phenotype_project/gene2phenotype_app/serializers/meta.py
gene2phenotype_project/gene2phenotype_app/urls.py
gene2phenotype_project/gene2phenotype_app/views/__init__.py
gene2phenotype_project/gene2phenotype_app/views/meta.py

[G2P-439](https://www.ebi.ac.uk/panda/jira/browse/G2P-439)

Reference data endpoint  - G2P-439

---

gene2phenotype_project/gene2phenotype_app/views/panel.py

Updates
- fixes gene omim id, HGNC id and synonyms
- return unique variant types
- return unique phenotypes
- rename `inferred variant consequence` to `variant consequence` - we already have both evidence/inferred in the db
- remove new lines from comments

Fix bug in download file

---

gene2phenotype_project/gene2phenotype_app/tests/views/test_disease.py

Ticket: [G2P-244](https://www.ebi.ac.uk/panda/jira/browse/G2P-244)

Add unit tests - disease

---

gene2phenotype_project/gene2phenotype_app/fixtures/ontology_term.json
gene2phenotype_project/gene2phenotype_app/fixtures/publication.json
gene2phenotype_project/gene2phenotype_app/tests/views/test_phenotype.py
gene2phenotype_project/gene2phenotype_app/tests/views/test_publication.py

Ticket: [G2P-245](https://www.ebi.ac.uk/panda/jira/browse/G2P-245)

Add unit tests - publications and phenotypes

---

gene2phenotype_project/gene2phenotype_app/tests/views/test_search.py

Ticket: [G2P-248](https://www.ebi.ac.uk/panda/jira/browse/G2P-248)

Add unit tests - search

---

gene2phenotype_project/gene2phenotype_app/serializers/user.py

Cherry-pick this fix from release/v2 https://github.com/EBI-G2P/gene2phenotype_api/pull/113

Fix method check_panel_permission

---

gene2phenotype_project/gene2phenotype_app/serializers/publication.py
gene2phenotype_project/gene2phenotype_app/utils/__init__.py
gene2phenotype_project/gene2phenotype_app/utils/publication_utils.py
gene2phenotype_project/gene2phenotype_app/views/publication.py

Ticket: [G2P-371](https://www.ebi.ac.uk/panda/jira/browse/G2P-371)

Add method to utils to clean publication title

---

gene2phenotype_project/gene2phenotype_app/tests/views/test_user.py

Test is failing because of the changes to the url that was merged later on. This will fix this.

Fixes for the test

---

gene2phenotype_project/gene2phenotype_app/fixtures/curation_data.json
gene2phenotype_project/gene2phenotype_app/fixtures/g2p_stable_id.json
gene2phenotype_project/gene2phenotype_app/tests/curation/test_add_curation.py

Code changes related to [G2P-478](https://www.ebi.ac.uk/panda/jira/browse/G2P-478).

G2P-478 - Unit tests for Add Curation endpoint

---

gene2phenotype_project/gene2phenotype_app/models.py
gene2phenotype_project/gene2phenotype_app/views/disease.py

Ticket: [G2P-495](https://www.ebi.ac.uk/panda/jira/browse/G2P-495)
Add new table: `external_disease`
Update endpoint: `external_disease/<ids>/`

Add table 'external_disease' to store all Mondo IDs

---

gene2phenotype_project/gene2phenotype_app/serializers/curation.py
gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/utils/curation_schema.json
gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/views/publication.py

This PR is necessary for this ticket [G2P-456](https://www.ebi.ac.uk/panda/jira/browse/G2P-456)

Support multiple mechanism synopsis

---

gene2phenotype_project/gene2phenotype_app/views/meta.py

Same as https://github.com/EBI-G2P/gene2phenotype_api/pull/177

Fix reference data (main)

---

gene2phenotype_project/gene2phenotype_app/urls.py
gene2phenotype_project/gene2phenotype_app/views/__init__.py
gene2phenotype_project/gene2phenotype_app/views/disease.py

Ticket: [G2P-516](https://embl.atlassian.net/browse/G2P-516)
New endpoint: `update/ontology_terms/`
Used by: https://github.com/EBI-G2P/gene2phenotype_scripts/pull/12

Add new endpoint to update or delete ontology terms in bulk

---

gene2phenotype_project/gene2phenotype_app/management/commands/check_data.py
gene2phenotype_project/gene2phenotype_app/management/commands/datachecks/Disease.py
gene2phenotype_project/gene2phenotype_app/management/commands/datachecks/MutationConsequence.py
gene2phenotype_project/gene2phenotype_app/management/commands/datachecks/__init__.py
gene2phenotype_project/gene2phenotype_app/utils/__init__.py
gene2phenotype_project/gene2phenotype_app/utils/disease_utils.py
gene2phenotype_project/gene2phenotype_project/settings.py

Ticket: [G2P-508](https://embl.atlassian.net/browse/G2P-508)
This check compares the disease name against the associated OMIM/Mondo disease name.
It calculates a similarity score, and returns scores < 0.3
This check is a WARNING - I configured the checks to have different levels in settings.py

Add data check - check disease cross references

---

gene2phenotype_project/gene2phenotype_app/fixtures/lgd_panel.json
gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py

Ticket: [G2P-520](https://embl.atlassian.net/browse/G2P-520)
Example to test: G2P03144

Fix panel list on the lgd endpoint

---

gene2phenotype_project/gene2phenotype_app/tests/curation/test_get_curation.py
gene2phenotype_project/gene2phenotype_app/tests/curation/test_list_curation.py

Unit tests for list curation drafts endpoint and get curation draft endpoint.
---
[G2P-480](https://embl.atlassian.net/browse/G2P-480)
---
---

G2P-480 - Unit tests for list curation drafts endpoint and get curation draft endpoint

---

gene2phenotype_project/gene2phenotype_project/settings.py

Changing the Refresh token lifetime from 1 day to 12hrs
---
[G2P-539](https://embl.atlassian.net/browse/G2P-539)
---
---

Changing from 1 day to 12hrs

---

gene2phenotype_project/gene2phenotype_app/fixtures/publication.json
gene2phenotype_project/gene2phenotype_app/fixtures/publication_comment.json
gene2phenotype_project/gene2phenotype_app/serializers/publication.py
gene2phenotype_project/gene2phenotype_app/tests/views/test_locus_genotype_disease.py

Update the publication comments to return the date with the following format: YYYY-MM-DD
---
No jira ticket - this is a quick fix.
---
---

Update date format of the publication comment

---

gene2phenotype_project/gene2phenotype_app/tests/views/test_panel.py
gene2phenotype_project/gene2phenotype_app/views/panel.py
gene2phenotype_project/schema.json

We allow the download of individual panels. Some collaborators requested we allow the download of all panels.
In this PR, I updated the endpoint `/panel/<name>/download` to accept name=`all`. The output file returns all G2P records.
I also formatted the code with Ruff - to review the actual code updates please check [this commit](https://github.com/EBI-G2P/gene2phenotype_api/commit/1d9c92a8ed84bc71b827d1d7f7931b22d31bf56e).
---
[G2P-460](https://embl.atlassian.net/browse/G2P-460)
---
---

Update endpoint /panel/name/download to allow downloading all panels

---

gene2phenotype_project/gene2phenotype_app/serializers/curation.py
gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/views/publication.py

Improve the error message when trying to add a mechanism categorisation that does not match the mechanism.
---
No JIRA ticket.
---
---

Improve error messages

---

gene2phenotype_project/gene2phenotype_app/fixtures/lgd_cross_cutting_modifier.json
gene2phenotype_project/gene2phenotype_app/tests/views/test_panel.py
gene2phenotype_project/gene2phenotype_app/views/panel.py

Updates to the download file:
- add column `molecular mechanism support`
- fix the value under `molecular mechanism categorisation`
---
[G2P-548](https://embl.atlassian.net/browse/G2P-548)
---
> [!WARNING]
> On release day update the FTP docs with new file format 
---

Fix mechanism categorisation in the download file

---

gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py

Update endpoint `gene2phenotype/api/molecular_mechanisms/` to return sorted mechanism values.
---
No ticket
---
---

Update molecular mechanism endpoint to return sorted mechanisms

---

gene2phenotype_project/gene2phenotype_app/fixtures/disease.json
gene2phenotype_project/gene2phenotype_app/fixtures/g2p_stable_id.json
gene2phenotype_project/gene2phenotype_app/fixtures/lgd_panel.json
gene2phenotype_project/gene2phenotype_app/fixtures/locus_genotype_disease.json
gene2phenotype_project/gene2phenotype_app/tests/curation/test_publish.py
gene2phenotype_project/gene2phenotype_app/tests/views/test_locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/tests/views/test_search.py
gene2phenotype_project/gene2phenotype_app/views/base.py
gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/views/search.py

Update the following endpoints to return merged records:
- `lgd/<stable_id>/`
- `search`
The endpoints returns the status code `HTTP_410_GONE`
---
[G2P-571](https://embl.atlassian.net/browse/G2P-571)
---
---

Update lgd and search endpoints to return merged records

---

gene2phenotype_project/gene2phenotype_app/tests/delete_data/test_delete_lgd_phenotype_summary.py
gene2phenotype_project/gene2phenotype_app/tests/delete_data/test_delete_lgd_variant_type_description.py
gene2phenotype_project/gene2phenotype_app/tests/insert_data/test_add_variant_type_description.py
gene2phenotype_project/gene2phenotype_app/tests/update_data/test_update_lgd_confidence.py
gene2phenotype_project/gene2phenotype_app/tests/update_data/test_update_lgd_mechanism.py
gene2phenotype_project/gene2phenotype_app/views/base.py
gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py

- Add more unit tests
- Improve the endpoint to delete variant descriptions
---
[G2P-491](https://embl.atlassian.net/browse/G2P-491)
---
---

Add more unit tests and other small improvements

---

gene2phenotype_project/gene2phenotype_app/fixtures/user_panels.json
gene2phenotype_project/gene2phenotype_app/serializers/user.py
gene2phenotype_project/gene2phenotype_app/tests/views/test_user.py

Update the login response to include `is_superuser` flag.
---
No ticket
---
---

Update login response and add tests

---

gene2phenotype_project/gene2phenotype_app/serializers/user.py
gene2phenotype_project/gene2phenotype_app/tests/views/test_user.py

Update `user_name` to `full_name` in the response.
Endpoint: `gene2phenotype/api/profile/`
---
No jira ticket
---
---

Update user profile response

---

gene2phenotype_project/gene2phenotype_app/management/commands/load_mined_publications.py
gene2phenotype_project/gene2phenotype_app/tests/commands/test_load_mined_publications.py
gene2phenotype_project/gene2phenotype_app/tests/insert_data/test_add_ccms.py
gene2phenotype_project/gene2phenotype_app/tests/insert_data/test_add_comments.py
gene2phenotype_project/gene2phenotype_app/tests/insert_data/test_add_panel.py
gene2phenotype_project/gene2phenotype_app/tests/insert_data/test_add_phenotypes.py

Run command:
`python manage.py load_mined_publications --data_file ddg2p_db.csv --email <email>`
Input file format:
```
PMID	G2P_IDs
7866404	G2P00037;G2P00798
7866411	G2P00275
```
Check jira ticket for details about the test data.
Related to https://github.com/EBI-G2P/gene2phenotype_api/pull/245
---
[G2P-598](https://embl.atlassian.net/browse/G2P-598)
---
---

Add management command to load mined publications

---

README.md
gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py

Code improvements and update README.
---
Not applicable.
---
---

Code improvements and update README

---

gene2phenotype_project/gene2phenotype_app/fixtures/g2p_stable_id.json
gene2phenotype_project/gene2phenotype_app/fixtures/lgd_panel.json
gene2phenotype_project/gene2phenotype_app/fixtures/lgd_publication.json
gene2phenotype_project/gene2phenotype_app/fixtures/lgd_variant_consequence.json
gene2phenotype_project/gene2phenotype_app/fixtures/locus_genotype_disease.json
gene2phenotype_project/gene2phenotype_app/tests/curation/test_publish.py
gene2phenotype_project/gene2phenotype_app/tests/delete_data/test_delete_lgd.py
gene2phenotype_project/gene2phenotype_app/tests/delete_data/test_delete_lgd_panel.py
gene2phenotype_project/gene2phenotype_app/tests/delete_data/test_delete_lgd_publication.py
gene2phenotype_project/gene2phenotype_app/tests/insert_data/test_add_variant_types.py
gene2phenotype_project/gene2phenotype_app/tests/update_data/test_update_mechanism.py
gene2phenotype_project/gene2phenotype_app/tests/views/test_gene.py
gene2phenotype_project/gene2phenotype_app/tests/views/test_locus_genotype_disease.py
gene2phenotype_project/gene2phenotype_app/tests/views/test_panel.py
gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py

Add unit tests for update record mechanism endpoint and minor fix to code. Also, removes duplicate fixtures in other unit test classes.
---
[G2P-484](https://embl.atlassian.net/browse/G2P-484)
---
---

G2P-484 - Add unit tests for update record mechanism endpoint

---

gene2phenotype_project/gene2phenotype_app/views/meta.py

Endpoint: `gene2phenotype/api/activity_logs/`
Update the endpoint to also return results for deleted records.
---
No ticket
---
---

Update endpoint activity_logs

---

requirements.txt

Upgrade Django version because of vulnerability.
I installed the new version locally and run all unit tests succesfully.
---
No ticket
---
---

Upgrade django version to 5.1.12

---

gene2phenotype_project/gene2phenotype_app/serializers/disease.py
gene2phenotype_project/gene2phenotype_app/tests/insert_data/test_add_disease.py
gene2phenotype_project/gene2phenotype_app/views/disease.py

Small fixes
---
No ticket
---
---

Small updates to diseases
