- gene2phenotype_project/gene2phenotype_app/models.py
- gene2phenotype_project/gene2phenotype_app/serializers.py
- gene2phenotype_project/gene2phenotype_app/utils/__init__.py
- gene2phenotype_project/gene2phenotype_app/utils/disease_utils.py
OMIM IDs should be stored in table ontology_term and linked to the disease in table disease_ontology.
This PR removes the column 'mim' from disease and adds the necessary updates to the API to accept/save OMIM IDs in the correct table.
> Update schema to remove mim from disease table

- gene2phenotype_project/gene2phenotype_app/views/curation.py
Just a quick fix for save and publishing, the stableid is part of the JSONResponse because thats how the stableID is retrieved for publish when it has been saved.
> To allow for publish

- gene2phenotype_project/gene2phenotype_app/serializers/disease.py
- gene2phenotype_project/gene2phenotype_app/serializers/locus.py
- gene2phenotype_project/gene2phenotype_app/serializers/panel.py
- gene2phenotype_project/gene2phenotype_app/views/panel.py
Test the following endpoints (without login)
- https://wwwdev.ebi.ac.uk/gene2phenotype/api/disease/CDH1-related%20prostate%20cancer%20test%2057/summary/
The disease summary returns refuted records even though I am not logged in -> incorrect
- https://wwwdev.ebi.ac.uk/gene2phenotype/api/lgd/G2P03879/
The LGD page does not allow non-authenticated users to access a refuted record -> correct
> Fix endpoints that return a summary of records

- gene2phenotype_project/gene2phenotype_app/serializers/curation.py
- gene2phenotype_project/gene2phenotype_app/serializers/disease.py
- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
The current code does not allow the publishing of a record if another record already uses the disease name.
This PR fixes the way the disease and disease-ontology are created.
To test: try to publish a record with a disease that already exists in table 'disease'
> Fix bug in curation/draft endpoint

- gene2phenotype_project/gene2phenotype_app/views/panel.py
Update the endpoint `gene2phenotype/api/panel/<panel_name>/download/` to return an uncompressed file.
New format: `.csv`
Ticket: [G2P-298](https://www.ebi.ac.uk/panda/jira/browse/G2P-298)
Test db: dlemos_G2P_2024_v17 or G2P_2024_v17
> Update the panel download file format

- gene2phenotype_project/gene2phenotype_app/views/search.py
The search matches the disease using `icontains`. This returns matches like this:
`gene2phenotype/api/search/?query=CDH1`
Matches:
```
{
"id": "G2P01046",
"gene": "PCDH19",
"genotype": "monoallelic_X_heterozygous",
"disease": "PCDH19-related EPILEPTIC ENCEPHALOPATHY EARLY INFANTILE TYPE 9",
"mechanism": "loss of function",
"panel": [
"DD"
]
}
```
Which is incorrect.
This PR improves this search.
> Improve search

- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/serializers/panel.py
After an update to the Locus Genotype Disease obj, we have to ensure the 'date_review' reflects the date of the latest update. 
This PR updates the 'date_review' after updating a G2P record (LGD).
The update affects the following endpoints:
```
gene2phenotype/api/lgd/<str:stable_id>/update_confidence/
gene2phenotype/api/lgd/<str:stable_id>/panel/
```
> Update date_review after LGD updates

- .github/workflows/test.yml
- gene2phenotype_project/gene2phenotype_app/serializers/curation.py
- gene2phenotype_project/gene2phenotype_app/views/search.py
Ticket: [G2P-311](https://www.ebi.ac.uk/panda/jira/browse/G2P-311)
Output format for search type `gene`:
```
{
"id": "G2P02001",
"gene": "CDH1",
"genotype": "monoallelic_autosomal",
"disease": "Blepharo-cheiro-dontic syndrome",
"mechanism": "undetermined",
"panel": [
"DD"
],
"confidence": "definitive"
}
```
Output format for search type `draft`:
```
{
"id": "G2P03716",
"gene": "CDH1",
"date_created": "2024-10-10T15:20:33.620010Z",
"date_last_updated": "2024-10-10T15:20:33.620010Z",
"curator_first": "Diana",
"curator_last_name": "Lemos",
"genotype": "biallelic_PAR",
"disease_name": "test name",
"panels": [
"Demo"
],
"confidence": "disputed",
"curator_email": "email@email.com"
}
```
Note: the failing tests are not related to this update.
> Update search to return the confidence

- gene2phenotype_project/gene2phenotype_app/serializers/curation.py
- gene2phenotype_project/gene2phenotype_app/serializers/publication.py
The user obj is missing from PublicationSerializer context.
**Testing**
Try to create a new record with a publication comment.
> Fix bug - add publication comment

- gene2phenotype_project/gene2phenotype_app/serializers/__init__.py
- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/urls.py
- gene2phenotype_project/gene2phenotype_app/views/__init__.py
- gene2phenotype_project/gene2phenotype_app/views/base.py
- gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
Ticket: [G2P-182](https://www.ebi.ac.uk/panda/jira/browse/G2P-182)
We only allow updates if the mechanism is 'undetermined'.
**New endpoint**
`gene2phenotype/api/lgd/<str:stable_id>/update_mechanism/`
The input data has the same format as the mechanism data sent by the curation page.
**To test** 
db: dlemos_G2P_2024_18
Input data:
```
{
"molecular_mechanism": {
"name": "gain of function",
"support": "evidence"
},
"mechanism_synopsis": {
"name": "",
"support": ""
},
"mechanism_evidence": [
{
"pmid": "18247425",
"description": "This is description for the mechanism evidence.",
"evidence_types": [
{
"primary_type": "Function",
"secondary_type": [
"Biochemical"
]
},
{
"primary_type": "Rescue",
"secondary_type": [
"Human",
"Patient Cells"
]
}
]
}
]
}
```
> Add endpoint to update molecular mechanism

- gene2phenotype_project/gene2phenotype_app/serializers/locus.py
Update endpoint `gene2phenotype/api/gene/<gene_name>/function/` to return the gene_stats rounded to three decimal places.
This updates is part of this ticket: [G2P-344](https://www.ebi.ac.uk/panda/jira/browse/G2P-344)
> Update gene scores to three decimal places

- gene2phenotype_project/gene2phenotype_app/serializers/disease.py
The endpoint gene2phenotype/api/disease/<disease_name>/summary/
returns `disease` under `records_summary`
Instead it should return the `locus`
In this PR I also updated the way the query is done, there were two queries being done now it's only one.
> Update disease summary endpoint

- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/serializers/phenotype.py
- gene2phenotype_project/gene2phenotype_app/serializers/publication.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_molecular_mechanism.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_variant_type.py
- gene2phenotype_project/gene2phenotype_app/views/base.py
- gene2phenotype_project/gene2phenotype_app/views/publication.py
To insert a new publication the endpoint also allows to insert optional fields:
- `phenotypes` linked to new and/or existing publications
- `variant types` linked to new and/or existing publications
- `variant descriptions` linked to new and/or existing publications
- `mechanism` linked to new and/or existing publications (Note: only "undetermined" mechanisms can be updated)
- `mechanism evidence` linked to new and/or existing publications
**Testing**
The input format is the same as the draft json data.
Input example:
```
{ "publications":[{
"publication": { "pmid": 1234 },
"comment": { "comment": "this is a comment", "is_public": 1 },
"families": { "families": 2, "consanguinity": "unknown", "ancestries": "african", "affected_individuals": 1    
}
}],
"phenotypes": [{
"pmid": "1234", …
```
> Update endpoint lgd-publication to support extra data

- gene2phenotype_project/gene2phenotype_app/serializers/curation.py
- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/serializers/panel.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/utils/curation_schema.json
Affected endpoints:
- curation: the JSON data now has the following format
```
"confidence": "strong"
"public_comment": "..."
"private_comment": "..."
```
- `lgd/str:stable_id/update_confidence/` does not accept `justification`
- `panel/name/summary/` rename 'date_review' to 'last_updated' and format date
> Update the way comments are saved

- gene2phenotype_project/gene2phenotype_app/serializers/locus.py
- gene2phenotype_project/gene2phenotype_app/serializers/panel.py
Ticket: [G2P-426](https://www.ebi.ac.uk/panda/jira/browse/G2P-426)
This PR also improves the records_summary method: now it only queries the db once.
> Return last_updated in gene summary

- gene2phenotype_project/gene2phenotype_app/views/user.py
Should log out exactly 24hrs after the first login and should not refresh the logout time after every token/refresh
> User log out fix

- gene2phenotype_project/gene2phenotype_app/urls.py
- gene2phenotype_project/gene2phenotype_app/views/__init__.py
- gene2phenotype_project/gene2phenotype_app/views/disease.py
New endpoints:
- `lgd_disease_updates/`: update the disease_id associated with the lgd record
- `update/diseases/`: update the disease name
> Add endpoints to support bulk updates of disease

- gene2phenotype_project/gene2phenotype_app/serializers/user.py
The method `check_panel_permission` does not have the intended behaviour.
Update the method to allow users to edit the record if they have permission to edit at least one of the panels linked to the record.
check_panel_permission is being called by [LGDEditComment](https://github.com/EBI-G2P/gene2phenotype_api/blob/release/v2/gene2phenotype_project/gene2phenotype_app/serializers/user.py#L87)
This bug affects the following endpoint:
`lgd/<str:stable_id>/comment/`
> Fix the permissions to add comments

- gene2phenotype_project/gene2phenotype_app/serializers/__init__.py
- gene2phenotype_project/gene2phenotype_app/serializers/phenotype.py
- gene2phenotype_project/gene2phenotype_app/views/phenotype.py
Ticket: [G2P-469](https://www.ebi.ac.uk/panda/jira/browse/G2P-469)
Endpoint: `lgd/<stable_id>/phenotypes`
**Input data**
- to add phenotypes and phenotype summary
```
{
"hpo_terms": [{
"accession": "HP:0003974",
"publication": 1
},{
"accession": "HP:0003349",
"publication": 1
},{
"accession": "HP:0003351",
"publication": 2
}],
"summaries": [{
"summary": "This is a summary",
"publication": [1]
},{
"summary": "This is a summary with a lot of phenotypes",
"publication": [2]
}]
}
```
- to only add phenotypes
```
{
"hpo_terms": [{
"accession": "HP:0003974",
"publication": 1
},{
"accession": "HP:0003349",
"publication": 1
}]
}
```
- to only add phenotype summaries
```
{
"summaries": [{
"summary": "This is a summary",
"publication": [1]
}]
}
```
> Update endpoint lgd/<stable_id>/phenotypes

- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
Ticket: [G2P-170](https://www.ebi.ac.uk/panda/jira/browse/G2P-170)
> Remove newline from comments

- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/serializers/publication.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_disease.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_publication.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_search.py
- gene2phenotype_project/gene2phenotype_app/views/attrib.py
- gene2phenotype_project/gene2phenotype_app/views/base.py
- gene2phenotype_project/gene2phenotype_app/views/curation.py
- gene2phenotype_project/gene2phenotype_app/views/disease.py
- gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/views/panel.py
- gene2phenotype_project/gene2phenotype_app/views/phenotype.py
- gene2phenotype_project/gene2phenotype_app/views/publication.py
This PR includes:
- update endpoints to print the error message under `error`, do not use `message` or `errors`.
- other small improvements
> Standardise error messages

- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/serializers/publication.py
The publication comments and variant type comments should only be available for authenticated users.
This PR updates the code to always save these comments as `is_public = 0` and only displays them when users are authenticated. 
Ticket: [G2P-463](https://www.ebi.ac.uk/panda/jira/browse/G2P-463)
> Make publication and variant type comments private

- gene2phenotype_project/gene2phenotype_app/fixtures/curation_data.json
- gene2phenotype_project/gene2phenotype_app/tests/curation/test_add_curation.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_panel.py
- gene2phenotype_project/gene2phenotype_app/views/base.py
- gene2phenotype_project/gene2phenotype_app/views/panel.py
Ticket: [G2P-512](https://www.ebi.ac.uk/panda/jira/browse/G2P-512)
Update the endpoint `gene2phenotype/api/panel/<name>/` to return 401 when the panel is valid but not visible.
> Update panel endpoint - fix authorisation issue

- README.md
- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/serializers/panel.py
- gene2phenotype_project/gene2phenotype_app/serializers/publication.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/views/panel.py
- gene2phenotype_project/gene2phenotype_app/views/phenotype.py
- gene2phenotype_project/gene2phenotype_app/views/publication.py
- gene2phenotype_project/schema.json
**Issues fixed in this PR**
- The column `locus_genotype_disease.date_review` doesn't always reflect the latest update
I updated the serializers and views to make sure each data update also updates the `date_review`
Note that if we insert a list of phenotypes then we should only update the date_review once - the code was updating `date_review` each time it inserted a phenotype which caused duplicated rows in the history table
- Remove `curators` from the lgd endpoint response
> Fix locus_genotype_disease.date_review updates

- gene2phenotype_project/gene2phenotype_app/tests/views/test_search.py
- gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/views/panel.py
- gene2phenotype_project/gene2phenotype_app/views/search.py
- gene2phenotype_project/schema.json
In search, the type `g2p_id` has been replaced by `stable_id` - this implies a web update.
The query is: `gene2phenotype/api/search/?query=G2P00001&type=stable_id`
Update can be tested on https://wwwdev.ebi.ac.uk/gene2phenotype/api/
> Public API - Improve public docs for search endpoint

- gene2phenotype_project/gene2phenotype_app/templates/swagger-ui.html
- gene2phenotype_project/schema.json
Remove the `Authorize` icon from the public API https://wwwdev.ebi.ac.uk/gene2phenotype/api/
---
No jira ticket, this is a hotfix.
---
---
> hotfix - remove authorize icon from the public api

- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/utils/__init__.py
- gene2phenotype_project/gene2phenotype_app/utils/lgd_utils.py
- gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/views/publication.py
Create method `validate_mechanism_synopsis()` in utils to run some checks.
The checks are:
- If mechanism is ‘undetermined’ categorisation cannot be set
- If mechanism is ‘undetermined non LOF’ categorisation cannot be set
- If mechanism is ‘loss of function’ categorisation should match LOF
- If mechanism is ‘dominant negative’ categorisation should match ‘dominant negative’
- If mechanism is ‘gain of function’ categorisation should match GOF, protein
These checks run for:
- publish record
- update record: when we add a new mechanism synopsis
- add new publication: when we add a new mechanism synopsis
This PR also fixes two bugs related to `check_user_permission()`:
- when calling this method we have to send the user in the context for the serializer.
- replace variable name `id` by …
> Restrict mechanism categorisation to match the mechanism value

- gene2phenotype_project/gene2phenotype_app/fixtures/locus_genotype_disease.json
- gene2phenotype_project/gene2phenotype_app/serializers/__init__.py
- gene2phenotype_project/gene2phenotype_app/serializers/disease.py
- gene2phenotype_project/gene2phenotype_app/serializers/locus.py
- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/serializers/panel.py
- gene2phenotype_project/gene2phenotype_app/tests/update_data/test_merge_records.py
- gene2phenotype_project/gene2phenotype_app/tests/update_data/test_update_lgd_review.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_panel.py
- gene2phenotype_project/gene2phenotype_app/urls.py
- gene2phenotype_project/gene2phenotype_app/views/__init__.py
- gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/views/panel.py
- gene2phenotype_project/schema.json
New endpoint to allow updating the review status of a record: `gene2phenotype/api/lgd/<stable_id>/review/`
Only available to super users.
Input data example: `{"is_reviewed": false}`
This PR also update the download file to include an extra column 'review' to flag which records are under review.
---
[G2P-522](https://embl.atlassian.net/browse/G2P-522)
---
---
> Add endpoint to update review status of the record

- gene2phenotype_project/gene2phenotype_app/fixtures/lgd_mechanism_evidence.json
- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
- gene2phenotype_project/schema.json
The mechanism evidence description is not being saved when record is published. 
Also update lgd endpoint to display the description for authenticated users. New format:
```
"molecular_mechanism": {
"mechanism": "gain of function",
"mechanism_support": "inferred",
"synopsis": [
{
"synopsis": "assembly-mediated GOF",
"support": "inferred"
}
],
"evidence": {
"4": {
"functional_studies": {
"Function": [
"Protein Interaction"
],
"Rescue": [
"Patient Cells"
],
"Functional Alteration": [
"Non Patient Cells"
]
},
"descriptions": [
"PMID: 4 functional studies",
"there is more evidence in the same PMID:4"
]
},
"12": {
"functional_studies": {
"Functional Alteration": [
"Patient Cells"
]
},
"descriptions": []
}
}
}
```
This change triggers a web update.
--- …
> Fix bug in mechanism evidence description

- gene2phenotype_project/gene2phenotype_project/settings.py
Set `SESSION_COOKIE_SECURE` to true to make sure the session cookie is only sent over HTTPS connections.
---
No ticket
---
---
> Add SESSION_COOKIE_SECURE to the settings

- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/tests/update_data/test_update_lgd_confidence.py
In this PR https://github.com/EBI-G2P/gene2phenotype_api/pull/212 the confidence was updated to be mandatory by mistake.
This PR adds the `required=False` back.
It also adds tests.
---
Test confidence update: [G2P-483](https://embl.atlassian.net/browse/G2P-483)
---
---
> Make is_reviewed optional when updating confidence

- gene2phenotype_project/gene2phenotype_app/fixtures/disease_external.json
- gene2phenotype_project/gene2phenotype_app/fixtures/user_panels.json
- gene2phenotype_project/gene2phenotype_app/tests/delete_data/test_delete_lgd_comment.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_disease.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_gene.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_panel.py
- gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
Improve endpoint `lgd/<str:stable_id>/comment/`
- The view is updating the flag `is_deleted` using method `update()` - this does not trigger history row. In this PR the code is updated to call `save()` making sure the history table is updated.
- Update the permissions: all authenticated users can add/delete comments.
- Add unit tests
---
[G2P-575](https://embl.atlassian.net/browse/G2P-575)
---
---
> Improve endpoint to delete LGD comments

- gene2phenotype_project/gene2phenotype_app/serializers/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/tests/delete_data/test_delete_lgd_comment.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
- Update the endpoint `gene2phenotype/api/lgd/<stable_id>` to return the lgd-comment id.
```
"comments": [
{
"id": 532,
"text": "Pathogenic variants",
"date": "2025-03-07",
"is_public": 1
}
]
```
- Update the endpoint `gene2phenotype/api/lgd/<stable_id>/comment/` to accept the comment id when deleting comments
To delete comment send the following:
`{"comment_id": 352}`
The web change is in the following PR: https://github.com/EBI-G2P/gene2phenotype_web/pull/150
---
No JIRA ticket
---
---
> Update lgd endpoint to return the lgd-comment primary key

- gene2phenotype_project/gene2phenotype_app/tests/views/test_locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/tests/views/test_search.py
- gene2phenotype_project/gene2phenotype_app/views/base.py
- gene2phenotype_project/gene2phenotype_app/views/locus_genotype_disease.py
- gene2phenotype_project/gene2phenotype_app/views/search.py
Update the following endpoints to return a message for deleted records:
- `lgd/<stable_id>/`
- `search`
Similar to https://github.com/EBI-G2P/gene2phenotype_api/pull/232
Web change: https://github.com/EBI-G2P/gene2phenotype_web/pull/154
---
[G2P-589](https://embl.atlassian.net/browse/G2P-589)
---
---
> Return message for deleted records

- gene2phenotype_project/gene2phenotype_app/serializers/__init__.py
- gene2phenotype_project/gene2phenotype_app/serializers/mined_publication.py
- gene2phenotype_project/gene2phenotype_app/tests/insert_data/test_add_publications.py
- gene2phenotype_project/gene2phenotype_app/views/publication.py
Extension to` /gene2phenotype/api/lgd/<stable_id>/publication/` endpoint.
When adding publications to existing record, we need to update status of the linked mined publications to "curated".
One of the changes as part of extending endpoints for mined publications ([G2P-550](https://embl.atlassian.net/browse/G2P-550)).
---
[G2P-550](https://embl.atlassian.net/browse/G2P-550)
---
---
> G2P-550 - When adding publications, update status of linked mined publications

- gene2phenotype_project/gene2phenotype_app/fixtures/disease_synonym.json
- gene2phenotype_project/gene2phenotype_app/tests/update_data/test_update_diseases.py
- gene2phenotype_project/gene2phenotype_app/views/disease.py
Update endpoint: `gene2phenotype/api/update/diseases/` to accept an optional value `add_synonym`. This allows to add the previous disease name as a synonym.
Example: Update the disease_id `2101` to the new name `SUFU-related medulloblastoma, associated with Gorlin syndrome` and add the current name as a synonym.
```
{
"id": 2101,
"name": "SUFU-related medulloblastoma, associated with Gorlin syndrome",
"add_synonym": True
}
```
---
Part of [G2P-545](https://embl.atlassian.net/browse/G2P-545)
---
---
> Endpoint update disease to support synonyms
